on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Test Run
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Launch the local action - requirements.txt
        uses: ./ # Uses an action in the root directory
        id: test
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset: test.png
          files: ./test/requirements.txt

      - name: Print the output
        run: |
          echo "Latest tag: ${{ steps.test.outputs.release_tag }}";
          echo "Update Available: ${{ steps.test.outputs.updated_packages }}";
          echo "Updated packages: ${{ steps.test.outputs.updated_packages }}";

      - name: Launch the local action - string
        uses: ./ # Uses an action in the root directory
        id: test2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          asset: test.png
          files: pyderman, requests, praw

      - name: Print the output
        run: |
          echo "Latest tag: ${{ steps.test2.outputs.release_tag }}";
          echo "Update Available: ${{ steps.test2.outputs.updated_packages }}";
          echo "Updated packages: ${{ steps.test2.outputs.updated_packages }}";
